import { compareVerseKeys } from '../data/quran'
import { ruleRunLetters } from '../lessons/quiz'
import type { VerseKey } from '../lessons/types'
import { segmentsToLetters } from '../tajweed/graphemes'
import { parseTajweed } from '../tajweed/parse'
import { confusableRules, TAJWEED_RULE_IDS, type TajweedRuleId } from '../tajweed/rules'

export const DIFFICULTIES = ['easy', 'medium', 'hard'] as const
export type Difficulty = (typeof DIFFICULTIES)[number]

/**
 * Quiz verses from the whole Quran (src/data/quiz-pool.json, generated by
 * `npm run build-quiz-pool` from the Quran Foundation API; never hand-edited).
 */
export interface QuizPool {
  source: { name: string; url: string; fetchedAt: string }
  /** `text_uthmani_tajweed` markup of every verse the tiers below list. */
  verses: Record<string, string>
  /** For each API rule, verse keys (mushaf order) that exercise it, by difficulty. */
  rules: Partial<Record<TajweedRuleId, Record<Difficulty, VerseKey[]>>>
}

/** How a verse exercises one rule: the numbers a difficulty tier is chosen from. */
export interface VerseRuleStats {
  /** Letters (graphemes, spaces excluded) in the verse. */
  letters: number
  /** Letters carrying the rule. */
  targets: number
  /** Distinct other API rules in the verse. */
  otherRules: number
  /** Letters carrying a rule easily confused with this one (see `confusableRules`). */
  confusables: number
  /** Letters without the rule on the same base letter as a target (a voweled qalqalah letter, an
   *  alif that isn't a madd): tapping by letter shape alone gets these wrong. */
  lookalikes: number
}

/**
 * - easy: a short ayah, one or two target letters, few other rules, and a look-alike rule only
 *   where it comes with each target (a lam shamsiyah always follows a hamzat al-wasl);
 * - hard: a long ayah with several target letters and many decoys to tell apart: look-alike
 *   rules and the same letters without the rule;
 * - medium: the rest, up to a length that still fits a phone screen.
 */
export const TIER_LIMITS = {
  easy: { maxLetters: 50, maxTargets: 2, maxOtherRules: 3 },
  hard: { minLetters: 100, maxLetters: 320, minTargets: 3, minDecoys: 6 },
  medium: { maxLetters: 200 },
} as const

/** The base letter of a grapheme (its first code point), without harakat. */
const baseOf = (letter: string) => String.fromCodePoint(letter.codePointAt(0)!)

/**
 * `rule`'s stats in `markup`, or undefined when the verse can't carry a question about it: the
 * rule is absent, or one of its spans holds no letter (only harakat or signs), which no letter
 * tap or highlight could stand for.
 */
export function verseRuleStats(markup: string, rule: TajweedRuleId): VerseRuleStats | undefined {
  const { runs, unplaced } = ruleRunLetters(markup, rule)
  if (runs.length === 0 || unplaced > 0) return undefined
  const letters = segmentsToLetters(parseTajweed(markup).segments).filter((l) => !l.isSpace)
  const confusable = new Set<string>(confusableRules(rule))
  const others = new Set(letters.map((l) => l.rule).filter((r) => r !== undefined && r !== rule))
  const targetBases = new Set(letters.filter((l) => l.rule === rule).map((l) => baseOf(l.text)))
  return {
    letters: letters.length,
    targets: runs.flat().length,
    otherRules: others.size,
    confusables: letters.filter((l) => l.rule !== undefined && confusable.has(l.rule)).length,
    lookalikes: letters.filter((l) => l.rule !== rule && targetBases.has(baseOf(l.text))).length,
  }
}

export function tierOf(stats: VerseRuleStats): Difficulty | undefined {
  const { easy, hard, medium } = TIER_LIMITS
  if (
    stats.letters >= hard.minLetters &&
    stats.letters <= hard.maxLetters &&
    stats.targets >= hard.minTargets &&
    stats.confusables + stats.lookalikes >= hard.minDecoys
  )
    return 'hard'
  if (
    stats.letters <= easy.maxLetters &&
    stats.targets <= easy.maxTargets &&
    stats.otherRules <= easy.maxOtherRules &&
    stats.confusables <= stats.targets
  )
    return 'easy'
  if (stats.letters <= medium.maxLetters) return 'medium'
  return undefined
}

/** `count` items spread evenly over `items` (all of them when there are fewer). */
function spread<T>(items: readonly T[], count: number): T[] {
  if (items.length <= count) return [...items]
  return Array.from({ length: count }, (_, i) => items[Math.floor(((i + 0.5) * items.length) / count)])
}

/**
 * Picks up to `perTier` verses per rule and difficulty from `verses` (verse key → markup),
 * spread across the whole Quran rather than bunched in one surah. Each (verse, rule) lands in at
 * most one tier, so a harder setting always draws different verses. Deterministic: the same
 * input gives the same pool.
 */
export function buildQuizPool(
  verses: Readonly<Record<string, string>>,
  { perTier, source }: { perTier: number; source: QuizPool['source'] },
): QuizPool {
  const keys = Object.keys(verses).sort(compareVerseKeys) as VerseKey[]
  const rules: QuizPool['rules'] = {}
  const used = new Set<string>()
  for (const rule of TAJWEED_RULE_IDS) {
    const candidates: Record<Difficulty, VerseKey[]> = { easy: [], medium: [], hard: [] }
    for (const key of keys) {
      const stats = verseRuleStats(verses[key], rule)
      const tier = stats && tierOf(stats)
      if (tier) candidates[tier].push(key)
    }
    const picked = {
      easy: spread(candidates.easy, perTier),
      medium: spread(candidates.medium, perTier),
      hard: spread(candidates.hard, perTier),
    }
    if (DIFFICULTIES.every((d) => picked[d].length === 0)) continue
    rules[rule] = picked
    for (const d of DIFFICULTIES) for (const key of picked[d]) used.add(key)
  }
  const poolVerses = Object.fromEntries(keys.filter((key) => used.has(key)).map((key) => [key, verses[key]]))
  return { source, verses: poolVerses, rules }
}
