/** Kept separate from the component registry so lesson data stays React-free. */
export type AnimationId =
  | 'qalqalah-bounce'
  | 'makharij-areas'
  | 'makharij-jawf'
  | 'makharij-halq'
  | 'makharij-lisan'
  | 'makharij-shafatan'
  | 'makharij-khayshum'
  | 'foundations-harakat' | 'foundations-sukun-shadda' | 'foundations-tanween'
  | 'idgham-ghunnah' | 'idgham-wo-ghunnah'
  | 'natural-madd'
  | 'madd-muttasil'
  | 'madd-munfasil'
  | 'madd-lazim-bar'
  | 'madd-lazim-cause'
  | 'izhar-clip'
  | 'iqlab-meem'
  | 'madd-arid' | 'madd-leen' | 'madd-badal' | 'madd-iwad' | 'madd-silah'
  | 'lam-shamsiyyah' | 'lam-qamariyyah' | 'lam-allah'
