/** Kept separate from the component registry so lesson data stays React-free. */
export type AnimationId =
  | 'qalqalah-bounce'
  | 'ikhfa-hidden'
  | 'makharij-areas'
  | 'makharij-jawf'
  | 'makharij-halq'
  | 'makharij-lisan'
  | 'makharij-shafatan'
  | 'makharij-khayshum'
  | 'foundations-harakat' | 'foundations-sukun' | 'foundations-shadda' | 'foundations-tanween'
  | 'idgham-ghunnah' | 'idgham-wo-ghunnah'
  | 'natural-madd'
  | 'madd-muttasil'
  | 'madd-munfasil'
  | 'madd-lazim-bar'
  | 'madd-lazim-cause'
  | 'izhar-clip'
  | 'iqlab-meem'
  | 'idgham-mithlayn' | 'idgham-mutajanisayn' | 'idgham-mutaqaribayn'
  | 'madd-arid' | 'madd-leen' | 'madd-badal' | 'madd-iwad' | 'madd-silah'
  | 'lam-shamsiyyah' | 'lam-qamariyyah' | 'lam-allah'
  | 'heavy-light'
  | 'ghunnah'
  | 'ra-vowel' | 'ra-sakinah' | 'ra-waqf'
  | 'hamzat-wasl' | 'hamzat-wasl-vowel' | 'silent-letters'
  | 'waqf-signs' | 'waqf-stop' | 'waqf-restart'
  | 'sifat-hams-jahr' | 'sifat-shiddah-rakhawah' | 'sifat-istila-istifal' | 'sifat-itbaq-infitah' | 'sifat-idhlaq-ismat' | 'sifat-safir-qalqalah-lin' | 'sifat-inhiraf-istitalah' | 'sifat-compare'
  | 'meem-ikhfa-shafawi' | 'meem-idgham-shafawi' | 'meem-izhar-shafawi'
