import type { QuizPool } from '../quiz/pool'

/**
 * The quiz pool (src/data/quiz-pool.json, generated by `npm run build-quiz-pool`; do not edit the
 * JSON). Loaded on demand so its few hundred KB stay out of the first page load; the build emits
 * it as its own chunk, which the service worker precaches for offline use.
 */
export const loadQuizPool = (): Promise<QuizPool> => import('./quiz-pool.json').then((m) => m.default as QuizPool)
