import type { QuizPool } from '../quiz/pool'
import { reloadOnFailedImport } from '../reloadOnFailedImport'

/**
 * The quiz pool (src/data/quiz-pool.json, generated by `npm run build-quiz-pool`; do not edit the
 * JSON). Loaded on demand so its few hundred KB stay out of the first page load; the build emits
 * it as its own chunk, which the service worker precaches for offline use (a page open since
 * before a deploy reloads once to find the new chunk: reloadOnFailedImport).
 */
export const loadQuizPool = (): Promise<QuizPool> =>
  reloadOnFailedImport(() => import('./quiz-pool.json')).then((m) => m.default as QuizPool)
