import type { Bilingual } from '../i18n/bilingual'
import type { VerseKey, WordKey } from '../lessons/types'
// `type: 'json'`: the Playwright suite imports clips (which read words from here) under Node's
// ESM loader, which requires the attribute.
import quran from './quran.json' with { type: 'json' }
import quranWords from './quran-words.json' with { type: 'json' }
import surahs from './surahs.json' with { type: 'json' }

/** Raw `text_uthmani_tajweed` markup, generated by `npm run fetch-quran`. Do not edit the JSON. */
export function getVerseMarkup(key: VerseKey): string | undefined {
  return (quran.verses as Record<string, string>)[key]
}

export const QURAN_SOURCE = quran.source

/**
 * Mushaf order for `surah:ayah` keys (and `surah:ayah:word` keys, which also compare by word
 * position), for `Array.prototype.sort`.
 */
export function compareVerseKeys(a: string, b: string): number {
  const pa = a.split(':').map(Number)
  const pb = b.split(':').map(Number)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0)
    if (diff !== 0) return diff
  }
  return 0
}

/** Per-ayah recitation (Mishary Alafasy) from EveryAyah, e.g. 112:1 → .../112001.mp3 */
export function verseAudioUrl(key: VerseKey): string {
  const [surah, ayah] = key.split(':').map((n) => n.padStart(3, '0'))
  return `https://everyayah.com/data/Alafasy_128kbps/${surah}${ayah}.mp3`
}

/**
 * The recitation clips play word by word: Mahmoud Khalil al-Husary, murattal, riwayat Hafs —
 * `id` is its Quran Foundation API recitation id, used by `npm run fetch-quran`.
 */
export const WORD_RECITATION: { id: number; reciter: Bilingual } = {
  id: 6,
  reciter: { ar: 'الشيخ محمود خليل الحصري', en: 'Sheikh Mahmoud Khalil al-Husary' },
}

/** One recited Quran word, as `npm run fetch-quran` stores it in src/data/quran-words.json. */
export interface QuranWord {
  /** `text_uthmani` from the API, verbatim. */
  text: string
  /** The ayah's audio file (`url`) and where this word is in it, in ms (`start` … `end`). */
  audio: { url: string; start: number; end: number }
}

/** A word's text and recited audio (WORD_RECITATION), generated by `npm run fetch-quran`. */
export function getWord(key: WordKey): QuranWord | undefined {
  return (quranWords.words as Record<string, QuranWord>)[key]
}

export const QURAN_WORDS_SOURCE = quranWords.source

/** A surah's name in Arabic and English, from src/data/surahs.json (`npm run fetch-quran`). */
export function surahName(surah: number): Bilingual {
  const name = (surahs.names as Record<string, Bilingual>)[surah]
  if (!name) throw new Error(`surah ${surah}: not in src/data/surahs.json`)
  return name
}

export const SURAHS_SOURCE = surahs.source

/** `1:1:3` → the ayah it is in (`1:1`) and its 1-based position there (3). */
export function splitWordKey(key: WordKey): { verseKey: VerseKey; position: number } {
  const [surah, ayah, position] = key.split(':')
  return { verseKey: `${Number(surah)}:${Number(ayah)}`, position: Number(position) }
}
