import quran from './quran.json'
import type { VerseKey } from '../lessons/types'

/** Raw `text_uthmani_tajweed` markup, generated by `npm run fetch-quran`. Do not edit the JSON. */
export function getVerseMarkup(key: VerseKey): string | undefined {
  return (quran.verses as Record<string, string>)[key]
}

export const QURAN_SOURCE = quran.source

/** Per-ayah recitation (Mishary Alafasy) from EveryAyah, e.g. 112:1 → .../112001.mp3 */
export function verseAudioUrl(key: VerseKey): string {
  const [surah, ayah] = key.split(':').map((n) => n.padStart(3, '0'))
  return `https://everyayah.com/data/Alafasy_128kbps/${surah}${ayah}.mp3`
}
