import { describe, expect, it } from 'vitest'
import surahs from './surahs.json' with { type: 'json' }
import { surahName, SURAHS_SOURCE } from './quran'

// src/data/surahs.json is generated by `npm run fetch-quran` from the API's chapters list.
describe('surah names (src/data/surahs.json)', () => {
  it('has all 114 surahs, each named in both languages, with its source', () => {
    for (let surah = 1; surah <= 114; surah++) {
      const name = surahName(surah)
      expect(name.ar.trim(), `surah ${surah}`).not.toBe('')
      expect(name.en.trim(), `surah ${surah}`).not.toBe('')
    }
    expect(Object.keys(surahs.names)).toHaveLength(114)
    expect(SURAHS_SOURCE.url).toMatch(/^https:\/\/api\.quran\.com\/.+chapters/)
  })

  it('throws for a surah that does not exist', () => {
    expect(() => surahName(115)).toThrow()
  })
})
